---
title: "VIBRANT Trial - Primary Analyses"
author: Laura Symul, Laura Vermeren, Susan Holmes
format: 
   html:
     page-layout: full
     code-fold: true
     toc: true
     toc-location: left
     toc-depth: 5
     embed-resources: true
execute:
  cache: true # true refresh false
  warning: false
knitr:
  opts_chunk:
    out.width: "100%"
editor: source
---

```{r libraries}
#| warning: false
#| cache: false

library(tidyverse)
library(magrittr)
library(gt)
library(patchwork)
library(SummarizedExperiment)
library(tidySummarizedExperiment)
library(brms)
library(gtsummary)
library(labelled)
library(scales)
# library(gridExtra)
library(ggpubr)
# library(mia) # BiocManager::install("mia")

theme_set(theme_light())
tmp <- fs::dir_map("R", source)
rm(tmp)

```

```{r source-utils}
#| warning: false
#| cache: false
tmp <- fs::dir_map("../VIBRANT-99-utils/R/", source)
rm(tmp)
```


This document presents the primary analyses of the VIBRANT trial. 


## Loading the data


```{r loading-mae}
#| eval: true

mae_files <- 
  fs::dir_ls(str_c(data_dir(), "04 unblinded MAEs/"), regexp = "mae_full_.*\\.rds$") |> 
  sort(decreasing = TRUE) |>
  magrittr::extract(1)

mae <- readRDS(mae_files)

rm(mae_files)

```


# Analyses

## Demographics (Table 1)

```{r 01-dem, child = '01-Demographics.qmd'}
#| eval: true
```

## Primary outcomes (Table 2)

```{r 02-primary, child = '02-primary-outcome.qmd'}
#| eval: true
```

## Secondary outcomes (Figures 2-4)

```{r 03-secondary, child = '03-secondary-outcomes.qmd'}
#| eval: true
```




